(ns ^:no-doc futurama.core-async-patching
  (:require
   [clojure.core.async :as async]
   [clojure.core.async.impl.go :as go-impl]
   [clojure.core.async.impl.ioc-macros :as rt])
  (:import
   [clojure.lang
    Var]
   [java.util.concurrent.atomic AtomicReferenceArray]))

;; Patched version of core.async's emit-state-machine to remove setting BINDINGS-IDX in finally
(defn emit-state-machine [machine num-user-params custom-terminators]
  (let [index (go-impl/index-state-machine machine)
        state-sym (with-meta (gensym "state_")
                    {:tag 'objects})
        local-start-idx (+ num-user-params rt/USER-START-IDX)
        state-arr-size (+ local-start-idx (go-impl/count-persistent-values index))
        local-map (atom {::go-impl/next-idx local-start-idx})]
    `(fn state-machine#
       ([] (rt/aset-all! (AtomicReferenceArray. (int ~state-arr-size))
             ~rt/FN-IDX state-machine#
             ~rt/STATE-IDX ~(:start-block machine)))
       ([~state-sym]
        (let [old-frame# (Var/getThreadBindingFrame)
              ret-value# (try
                           (Var/resetThreadBindingFrame (rt/aget-object ~state-sym ~rt/BINDINGS-IDX))
                           (loop []
                             (let [result# (case (int (rt/aget-object ~state-sym ~rt/STATE-IDX))
                                             ~@(mapcat
                                                 (fn [[id blk]]
                                                   [id `(let [~@(concat (#'go-impl/build-block-preamble local-map index state-sym blk)
                                                                        (#'go-impl/build-block-body state-sym blk))
                                                              ~@(#'go-impl/build-new-state local-map index state-sym blk)]
                                                          ~(go-impl/terminate-block (last blk) state-sym custom-terminators))])
                                                 (:blocks machine)))]
                               (if (identical? result# :recur)
                                 (recur)
                                 result#)))
                           (catch Throwable ex#
                             (rt/aset-all! ~state-sym ~rt/VALUE-IDX ex#)
                             (if (seq (rt/aget-object ~state-sym ~rt/EXCEPTION-FRAMES))
                               (rt/aset-all! ~state-sym ~rt/STATE-IDX (first (rt/aget-object ~state-sym ~rt/EXCEPTION-FRAMES)))
                               (throw ex#))
                             :recur)
                           (finally
                             (Var/resetThreadBindingFrame old-frame#)))]
          (if (identical? ret-value# :recur)
            (recur ~state-sym)
            ret-value#))))))

(alter-var-root #'go-impl/emit-state-machine (constantly emit-state-machine))

(defn ioc-take!
  "Calls core.async's `ioc-macros/take!` (the `<!` parking terminator), but snapshots the thread binding frame before registering the callback."
  [state blk c]
  (rt/aset-object state rt/BINDINGS-IDX (Var/getThreadBindingFrame))
  (rt/take! state blk c))

(defn ioc-put!
  "Calls core.async's `ioc-macros/put!` (the `>!` parking terminator), but snapshots the thread binding frame before registering the callback."
  [state blk c val]
  (rt/aset-object state rt/BINDINGS-IDX (Var/getThreadBindingFrame))
  (rt/put! state blk c val))

(defn ioc-alts!
  "Calls core.async's `ioc-alts!` (the `alts!` parking terminator), but snapshots the thread binding frame before registering the callback."
  [state cont-block ports & opts]
  (rt/aset-object state rt/BINDINGS-IDX (Var/getThreadBindingFrame))
  (apply async/ioc-alts! state cont-block ports opts))

(def async-custom-terminators
  "Custom parking terminators to snapshot the thread binding frame before registering the callback."
  (assoc rt/async-custom-terminators
         `async/<! `ioc-take!
         `async/>! `ioc-put!
         `async/alts! `ioc-alts!))

;;; JG:
;;; monkey patch core.async's async-custom-terminators to use our custom ones that snapshot the thread bindings.
;;; this is necessary because core.async's async-custom-terminators are used in the state machine generated by
;;; go blocks, and we want to ensure that the correct thread binding frame is used when resuming the state machine
;;; on another thread.
(alter-var-root #'rt/async-custom-terminators (constantly async-custom-terminators))
