name: Clojure CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

env:
  CLOJURE_CLI_VERSION: '1.12.5.1664'

jobs:
  test:
    strategy:
      matrix:
        java_distribution: [corretto]
        java_version: ['25']
        test_clojure_alias: [clojure-1.12]
        test_core_async_alias: [core.async-1.8, core.async-1.9]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v7
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: ${{matrix.java_distribution}}
        java-version: ${{matrix.java_version}}
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@13.6.1
      with:
        cli: ${{env.CLOJURE_CLI_VERSION}}
    - name: Cache Clojure dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-${{runner.os}}-${{hashFiles('deps.edn')}}
        restore-keys: cljdeps-${{runner.os}}-
    - name: Run tests
      env:
        TEST_CLOJURE_ALIAS: ${{matrix.test_clojure_alias}}
        TEST_CORE_ASYNC_ALIAS: ${{matrix.test_core_async_alias}}
      run: make test TEST_CLOJURE_ALIAS=$TEST_CLOJURE_ALIAS TEST_CORE_ASYNC_ALIAS=$TEST_CORE_ASYNC_ALIAS
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v7
    - name: Setup GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: '22.3.1'
        java-version: '11'
        components: 'native-image'
        github-token: ${{secrets.GITHUB_TOKEN}}
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@13.6.1
      with:
        cli: ${{env.CLOJURE_CLI_VERSION}}
    - name: Cache Clojure dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-${{runner.os}}-${{hashFiles('deps.edn')}}
        restore-keys: cljdeps-${{runner.os}}-
    - name: Run tests
      run: make test
    - name: Run clj-kondo linter
      run: make lint
    - name: Run build jar
      run: make build
    - name: Run build app
      run: |
        make build-native
        build/futurama-test-app this is a test invocation of native app
